// Generated by CoffeeScript 1.7.1
(function() {
  var Rect, Shape,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Shape = (function() {
    function Shape(x, y) {}

    setX;

    Shape.prototype.getX = function() {};

    return Shape;

  })();

  Rect = (function(_super) {
    __extends(Rect, _super);

    function Rect(x, y, w, h) {
      Rect.__super__.constructor.call(this, x, y);
      this.width = w;
      this.height = h;
    }

    return Rect;

  })(Shape);

}).call(this);

//# sourceMappingURL=script.map
